---
title: "EDA - Wild Boar forest project"
output: html_document
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

```{r, warning=F, message=F}
rm(list = ls())
```


```{r, warning=F, message=F}
library(ComputationalMovementAnalysisData)
library(tidyverse)
library(sf)
```


```{r, warning=F, message=F}
ws <- wildschwein_BE
metadata <- wildschwein_metadata
```

```{r}
names(ws)
n_distinct(ws$TierID)
```
```{r}

ws <- ws %>% 
  group_by(TierID) %>% 
  mutate(timelag = as.integer(difftime(lead(DatetimeUTC), DatetimeUTC, units = "secs"))) %>% 
  ungroup()

summary(ws$timelag)
# 19 NA's because of 19 distinct ID's
```

--------------------------------------------------------------------------------


# Exploring Sampling Intervals


```{r}
ws$TierID <- as.factor(ws$TierID)

p1 <- ws %>% ggplot(aes(x = DatetimeUTC, y = TierID, colour = TierID)) +
  geom_point(show.legend = F)

p1  
```

```{r}
range(ws$timelag, na.rm = T)
nrow(ws)

ws_range <- ws %>% filter(timelag >= 0 & timelag < 30000) 

range(ws_range$timelag, na.rm = T)
nrow(ws_range)

nrow(ws) - nrow(ws_range)
```


```{r}
ws_range %>% 
  ggplot(aes(x = timelag)) +
  geom_histogram(binwidth = 60) +
  scale_y_log10()
```


```{r, fig.height=8}
# p2 <- ws_range %>% ggplot(aes(x = DatetimeUTC, y = TierID, colour = TierID)) +
#   geom_point(show.legend = F)
# p2
# grid.arrange(p1,p2, nrow = 1)
```


```{r}
ws_range2 <- ws %>% filter(timelag >= 0 & timelag < 2000)

ws_range2 %>% 
  ggplot(aes(x = timelag)) +
  geom_histogram(binwidth = 1) +
  scale_y_log10()
```
- most sampling intervals are between 10 & 20 minutes

```{r}
# ws_60s <- ws %>% filter(timelag >= 0 & timelag < 500)
ws_60s <- ws %>% filter(timelag >= 50 & timelag < 70)

ws_60s %>% 
  ggplot(aes(x = timelag)) +
  geom_histogram(binwidth = 1) +
  scale_y_log10()

```
-> around 30000 sampling intervals are within 1 minute
```{r}
ws_60s <- ws_60s %>% filter(DatetimeUTC > "2015-01-01" & DatetimeUTC < "2016-01-01")

p3 <- ws_60s %>% ggplot(aes(x = DatetimeUTC, y = TierID, colour = TierID)) +
  geom_point(show.legend = F)

p3

```
--> Animal ID's c(10, 22, 36, 40, 48) have smapling interval's of one minute in overlapping times in the year 2015


```{r}
ws_names <- unique(ws_60s$TierName)


```



--------------------------------------------------------------------------------

# Pre-Analysis of Location

```{r}
sf_60s <- st_as_sf(ws_60s, coords = c("N","E"), crs = 2056)

sf_60s_grouped <- group_by(sf_60s, TierID)
```

## MCP

```{r}
sf_60s_smry <- summarise(sf_60s_grouped)
mcp <- st_convex_hull(sf_60s_smry)
```

```{r}
ggplot(mcp, ) + 
    aes(fill = TierID, alpha = 0.5) +
    geom_sf() +
    coord_sf(datum = sf::st_crs(2056))
```
--> Territoriality sex biased in wild boar?

```{r}
grid <- st_make_grid(sf_60s, square = F, cellsize = 1000)

grid_agg <- aggregate(sf_60s, grid, FUN = length) %>% select(TierID)


ggplot(grid_agg, aes(fill = TierID)) + geom_sf() + geom_sf(data = sf_60s, inherit.aes = FALSE)


```












