---
title: "Forests_vs_Rest"
output: html_document
date: "`r Sys.Date()`"
---
Forests_vs_Rest



```{r, warning=F, message=F}
rm(list = ls())
```

```{r, warning=F, message=F}
library(ComputationalMovementAnalysisData)
library(tidyverse)
library(sf)
library(tmap)
library(terra)
library(gridExtra)
library(data.table)

```

```{r, warning=F, message=F}
# Wild Boar data
ws <- wildschwein_BE
metadata <- wildschwein_metadata
metadata <- metadata %>% filter(TierID %in% c(10,22,36,40,48))

# Raster Map
underl_map <- terra::rast("pk100_BE.tif")

# Loading and preparing Forest Polygon
st_layers("Feldaufnahmen_Fanel.gpkg")
forest <- read_sf("Feldaufnahmen_Fanel.gpkg")
forest <- forest %>% filter(Frucht == "Wald")

```

```{r}
names(ws)
names(metadata)
n_distinct(ws$TierID)
n_distinct(ws$CollarID)
```


# Data Preparation
```{r}
ws <- merge(ws, metadata[, c("TierID","Sex")], by = "TierID")
ws <- merge(ws, metadata[, c("TierID","Study_area")], by = "TierID")
  
ws_fin <- ws %>% 
  subset(select = - c(CollarID, day, moonilumination)) %>% 
  filter(Study_area == "Bern")
```

```{r}
# remove ws whole data set (to save storage)
rm(ws)

```


# Transforming to SF
```{r}
ws_sf <- st_as_sf(ws_fin,
                coords = c("E", "N"), 
                crs = 2056)

# ws_sf_nonfactor <- ws_sf
ws_sf$TierID <- as.factor(ws_sf$TierID)

rm(ws_fin)
```



```{r}
# c(10, 22, 36, 40, 48))
ws_sf_dt <- ws_sf %>% filter(TierID %in% c(22)) %>% select(DatetimeUTC, TierID)
```

--------------------------------------------------------------------------------

forest - grid

```{r}
grid_area <- st_make_grid(ws_sf_dt, square = FALSE, cellsize = 100) %>%  st_as_sf() 


intersects <- st_intersects(grid_area,  forest)
grid_area$forest <- sapply(intersects, FUN = length) > 0
# Additional column in grid_area with T/F for Forest


grid_area <- grid_area %>% mutate(ID = row_number())

grid_agg <- st_join(ws_sf_dt, grid_area, left = FALSE)

by_cell <- grid_agg %>% group_by(ID,forest) %>% summarise(n = n())

new_agg <- st_join(grid_area, by_cell)
```

# Plot Variant 1
```{r, fig.height=5, fig.width=10}
tmap_mode("view")

A <- tm_shape(underl_map) +
      tm_rgb() +
      tm_shape(new_agg) +
      tm_polygons("n", alpha = 0.8, style = "cont", n = 30) +
      tm_layout(legend.outside = TRUE) +
      tm_facets(by = "forest.x", ncol = 2)

```


# Plot Variant 2
```{r}
new_agg_forest <- new_agg %>% filter(forest.x == TRUE) %>% drop_na()
new_agg_non_forest <- new_agg %>% filter(forest.x == FALSE) %>% drop_na()

B <- tm_shape(underl_map) +
      tm_rgb() +
      tm_shape(new_agg_forest) +
      tm_polygons("n", alpha = 0.8, style = "cont", n = 30, palette = "Greens", n = 100, contrast = c(0.35, 0.9)) +
      tm_borders(col = "black", lwd = 1, lty = "solid") +
      tm_shape(new_agg_non_forest) +
      tm_polygons("n", alpha = 0.8, style = "cont", n = 30, palette = "Reds", n = 100, contrast = c(0.35, 0.9)) +
      tm_layout(legend.outside = TRUE)

## -> As there are cells with 7'000 observations, the scaling is weird and cells with a few hundred obs are same colour as cells with 2 obs !
# -> maybe log scale ?   or sqrt scale ?
      

```
















