---
title: "Recurrence"
output: html_document
date: "`r Sys.Date()`"
---

Recurrence


```{r, warning=F, message=F}
rm(list = ls())
```

```{r, warning=F, message=F}
library(ComputationalMovementAnalysisData)
library(tidyverse)
library(sf)
library(tmap)
library(terra)
library(gridExtra)
library(data.table)

```

```{r, warning=F, message=F}
ws <- wildschwein_BE
metadata <- wildschwein_metadata
metadata <- metadata %>% filter(TierID %in% c(10,22,36,40,48))

underl_map <- terra::rast("pk100_BE.tif")

```

```{r}
names(ws)
names(metadata)
n_distinct(ws$TierID)
n_distinct(ws$CollarID)
```


# Data Preparation
```{r}
ws <- merge(ws, metadata[, c("TierID","Sex")], by = "TierID")
ws <- merge(ws, metadata[, c("TierID","Study_area")], by = "TierID")
  
ws_fin <- ws %>% 
  subset(select = - c(CollarID, day, moonilumination)) %>% 
  filter(Study_area == "Bern")
```

```{r}
# remove ws whole data set (to save storage)
rm(ws)

```


# Transforming to SF
```{r}
ws_sf <- st_as_sf(ws_fin,
                coords = c("E", "N"), 
                crs = 2056)

# ws_sf_nonfactor <- ws_sf
ws_sf$TierID <- as.factor(ws_sf$TierID)

rm(ws_fin)
```



```{r}
# c(10, 22, 36, 40, 48))

ws_sf_dt <- ws_sf %>% filter(TierID %in% c(40)) %>% select(DatetimeUTC, TierID)
```

```{r}
grid_area <- st_make_grid(ws_sf_dt, square = FALSE, cellsize = 150) %>%  st_as_sf() 

grid_area <- grid_area %>% mutate(ID = row_number())

grid_agg <- st_join(ws_sf_dt, grid_area, left = FALSE)

###
by_cell <- grid_agg %>% mutate(logic = ifelse(ID == lag(ID), TRUE, FALSE)) %>% group_by(ID) %>% count(logic) %>% filter(logic == FALSE)
###

new_agg <- st_join(grid_area, by_cell, by = ID) %>% drop_na()

```

Plot
```{r, fig.height=5, fig.width=10}
tmap_mode("view")

A <- tm_shape(underl_map) +
      tm_rgb() +
      tm_shape(new_agg) +
      tm_polygons("n", alpha = 0.8, style = "cont", palette = "Blues", n = 20) +
      tm_layout(legend.outside = TRUE)
    
```


# function to produce recurrence plots
```{r}
grid_recurr_plots <- function(data, underl_map, Cellsize){
  
  id_list <- unique(data$TierID)
  plot_list <- vector("list", length(id_list))
  agg_list  <- vector("list", length(id_list))
  
  data <- group_by(data, TierID)
  
  for (i in seq(1,length(id_list))){
    ws_temp <- filter(data, TierID == id_list[i]) %>% select(DatetimeUTC, TierID)
    
    grid_area <- st_make_grid(ws_temp, square = FALSE, cellsize = Cellsize, crs = 2056) %>% st_as_sf()
    grid_area <- grid_area %>% mutate(ID = row_number())
    
    grid_agg <- st_join(ws_temp, grid_area, left = FALSE)
    
    by_cell <- grid_agg %>% mutate(logic = ifelse(ID == lag(ID), TRUE, FALSE)) %>% group_by(ID) %>% count(logic) %>% filter(logic == FALSE)

    new_agg <- st_join(grid_area, by_cell)
    
    # var_name <- paste("P", id_list[i], sep = "")
    # agg_list[[i]] <- assign(var_name, new_agg)
    
    # Plot 
    p <-  tm_shape(underl_map) +
                      tm_rgb() +
                      tm_shape(new_agg) +
                      tm_polygons("n", alpha = 0.8, style = "cont") +
                      tm_layout(legend.outside = TRUE)

    # creating variable & append to plot list
    var_name <- paste("P", id_list[i], sep = "")
    # assign(var_name, p)
    plot_list[[i]] <- assign(var_name, p)
    
    
  }
  return(plot_list)
  # return(agg_list)
}

```



test function
```{r}
tmap_mode("plot")
# c(10, 22, 36, 40, 48))
ws_sf_dt <- ws_sf %>% filter(TierID %in% c(22, 36)) %>% select(DatetimeUTC, TierID)

plots <- grid_recurr_plots(ws_sf_dt, underl_map, 150)
Arranged_plots <- tmap_arrange(plots, ncol = 2)
```


```{r}
# plots
# Arranged_plots
```


# Plot with multiple layers: -> new function

```{r}
recurr_layer_plot <- function(data, underl_map, Cellsize){
  
  grid_area <- st_make_grid(data, square = FALSE, cellsize = Cellsize) %>%  st_as_sf() 
  grid_area <- grid_area %>% mutate(ID = row_number())

  grid_agg <- st_join(data, grid_area, left = FALSE)

  by_cell <- grid_agg %>% mutate(logic = ifelse(ID == lag(ID), TRUE, FALSE)) %>% group_by(ID) %>% count(logic) %>% filter(logic == FALSE)

  # Drop NA deletes the rest of the grid
  new_agg <- st_join(grid_area, by_cell, by = ID) %>% drop_na()
  
  return(new_agg)
}
```


```{r}
ws_sf_dt <- ws_sf %>% filter(TierID %in% c(22)) %>% select(DatetimeUTC, TierID)
Miriam <- recurr_layer_plot(ws_sf_dt, underl_map, 100)

ws_sf_dt <- ws_sf %>% filter(TierID %in% c(36)) %>% select(DatetimeUTC, TierID)
Olga <- recurr_layer_plot(ws_sf_dt, underl_map, 100)
```


```{r}
tmap_mode("view")

MO <- tm_shape(underl_map) +
        tm_rgb() +
        tm_shape(Miriam) +
        tm_polygons("n", alpha = 0.8, style = "cont", palette = "Blues", n = 30) +
        tm_layout(legend.show = FALSE)  +
        tm_shape(Olga) +
        tm_polygons("n", alpha = 0.8, style = "cont", palette = "Reds", n = 30) +
        tm_layout(legend.show = FALSE)

```


```{r}
ws_sf_dt <- ws_sf %>% filter(TierID %in% c(40)) %>% select(DatetimeUTC, TierID)
Franz <- recurr_layer_plot(ws_sf_dt, underl_map, 100)

ws_sf_dt <- ws_sf %>% filter(TierID %in% c(48)) %>% select(DatetimeUTC, TierID)
Amos <- recurr_layer_plot(ws_sf_dt, underl_map, 100)

```


```{r}
FA <- tm_shape(underl_map) +
        tm_rgb() +
        tm_shape(Franz) +
        tm_polygons("n", alpha = 0.8, style = "cont", palette = "Blues", n = 30) +
        tm_layout(legend.show = FALSE)  +
        tm_shape(Amos) +
        tm_polygons("n", alpha = 0.8, style = "cont", palette = "Reds", n = 30) +
        tm_layout(legend.show = FALSE)

```

























































