---
title: "Territories_with_st_join"
output: html_document
date: "`r Sys.Date()`"
---


```{r, warning=F, message=F}
rm(list = ls())
```

```{r, warning=F, message=F}
library(ComputationalMovementAnalysisData)
library(tidyverse)
library(sf)
library(tmap)
library(terra)
library(gridExtra)

```

```{r, warning=F, message=F}
ws <- wildschwein_BE
metadata <- wildschwein_metadata
metadata <- metadata %>% filter(TierID %in% c(10,22,36,40,48))

underl_map <- terra::rast("pk100_BE.tif")

```

```{r}
names(ws)
names(metadata)
n_distinct(ws$TierID)
n_distinct(ws$CollarID)
```



# Data Preparation
```{r}
ws <- merge(ws, metadata[, c("TierID","Sex")], by = "TierID")
ws <- merge(ws, metadata[, c("TierID","Study_area")], by = "TierID")
  
ws_fin <- ws %>% 
  subset(select = - c(CollarID, day, moonilumination)) %>% 
  filter(Study_area == "Bern")
```

```{r}
# remove ws whole data set (to save storage)
rm(ws)

```



# Transforming to SF
```{r}
ws_sf <- st_as_sf(ws_fin,
                coords = c("E", "N"), 
                crs = 2056)

# ws_sf_nonfactor <- ws_sf
ws_sf$TierID <- as.factor(ws_sf$TierID)

rm(ws_fin)
```




# function to produce a density (field) plot for each animal
```{r}

grid_join_plots <- function(data, underl_map, Cellsize){
  
  
  id_list <- unique(data$TierID)
  plot_list <- vector("list", length(id_list))
  
  data <- group_by(data, TierID)
  
  for (i in seq(1,length(id_list))){
    ws_temp <- filter(data, TierID == id_list[i]) %>% select(DatetimeUTC, TierID)
    
    grid_area <- st_make_grid(ws_temp, square = FALSE, cellsize = Cellsize, crs = 2056) %>% st_as_sf()
    grid_area <- grid_area %>% mutate(ID = row_number())
    
    grid_agg <- st_join(ws_temp, grid_area, left = FALSE)
    
    by_cell <- grid_agg %>% group_by(ID,TierID) %>% summarise(n = n())
    
    new_agg <- st_join(grid_area, by_cell)
    
    # Plot 
    p <-  tm_shape(underl_map) +
                      tm_rgb() +
                      tm_shape(new_agg) +
                      tm_polygons("n", alpha = 0.8, style = "cont", legend.hist = TRUE) +
                      tm_layout(legend.outside = TRUE))

    # creating variable & append to plot list
    var_name <- paste("P", id_list[i], sep = "")
    # assign(var_name, p)
    plot_list[[i]] <- assign(var_name, p)
    # plot_list[[i]] <- ws_temp
    
  }
  return(plot_list)
  # return(grid_agg)
}

```

-----------------------

```{r}
# c(10, 22, 36, 40, 48))

ws_sf_dt <- ws_sf %>% filter(TierID %in% c(48)) %>% select(DatetimeUTC, TierID)
```


```{r}
grid_area <- st_make_grid(ws_sf_dt, square = FALSE, cellsize = 150) %>%  st_as_sf() 

grid_area <- grid_area %>% mutate(ID = row_number())

grid_agg <- st_join(ws_sf_dt, grid_area, left = FALSE)

by_cell <- grid_agg %>% group_by(ID,TierID) %>% summarise(n = n())

new_agg <- st_join(grid_area, by_cell)
```


Plot

```{r, fig.height=5, fig.width=10}

tm_shape(underl_map) +
    tm_rgb() +
    tm_shape(new_agg) +
    tm_polygons("n", alpha = 0.8, style = "cont", legend.hist = TRUE) +
    tm_layout(legend.outside = TRUE)
    
```


- Test function

```{r}
ws_sf_dt <- ws_sf %>% filter(TierID %in% c(48)) %>% select(DatetimeUTC, TierID)

plots <- grid_join_plots(ws_sf_dt, underl_map, 100)

plots

```











- How do we filter the points between forest and not forest
- What could be a solution 
```{r}

```


forest - grid

```{r}
st_layers("Feldaufnahmen_Fanel.gpkg")

forest <- read_sf("Feldaufnahmen_Fanel.gpkg")

forest <- forest %>% filter(Frucht == "Wald")


intersects <- st_intersects(grid_area,  forest)

grid_area$wald <- sapply(intersects, FUN = length) > 0

```

































