---
title: "Trajectories_WildBoarData"
output: html_document
date: "`r Sys.Date()`"
---

```{r, warning=F, message=F}
rm(list = ls())
```


```{r, warning=F, message=F}
library(ComputationalMovementAnalysisData)
library(tidyverse)
library(sf)
```


```{r, warning=F, message=F}
ws <- wildschwein_BE
metadata <- wildschwein_metadata
```


```{r}
ws <- ws %>% 
  group_by(TierID) %>% 
  mutate(timelag = as.integer(difftime(lead(DatetimeUTC), DatetimeUTC, units = "secs"))) %>% 
  ungroup()

summary(ws$timelag)
# 19 NA's because of 19 distinct ID's
```

```{r}

ws$TierID <- as.factor(ws$TierID)

# Filtering and Removing some columns:
ws_range <- ws %>% 
  filter(timelag >= 0 & timelag < 30000) %>% 
  subset(select = - c(day, CollarID, moonilumination))
```


```{r}
# 60 second sampling interval
ws_60s <- ws_range %>% filter(timelag >= 50 & timelag < 70)
```

```{r}
# During the relevant and overlapping time
ws_60s <- ws_60s %>% filter(DatetimeUTC > "2015-01-01" & DatetimeUTC < "2016-01-01")


# Plot with the 5 overlapping individuals
p3 <- ws_60s %>% ggplot(aes(x = DatetimeUTC, y = TierID, colour = TierID)) +
  geom_point(show.legend = F)

p3

```


```{r}
range(ws$timelag, na.rm = T)
nrow(ws)

ws_range <- ws %>% filter(timelag >= 0 & timelag < 30000) 

range(ws_range$timelag, na.rm = T)
nrow(ws_range)

nrow(ws) - nrow(ws_range)
```


```{r}
ws_range %>% 
  ggplot(aes(x = timelag)) +
  geom_histogram(binwidth = 60) +
  scale_y_log10()
```


```{r}
derivates <- function(ws_60s){
    # timelag
    sf_data <- mutate(ws_60s, timelag = as.integer(difftime(lead(ws_60s$DatetimeUTC), ws_60s$DatetimeUTC, units = "secs")))
    # steplength
    ws_60s$steplength <- sqrt(((ws_60s$E - lead(ws_60s$E))**2) + ((ws_60s$N - lead(ws_60s$N))**2)) 
    # speed
    ws_60s$speed <- (ws_60s$steplength / ws_60s$timelag)
    
    ws_60s
}
```

```{r}
traj_map <- function(original, resampled, E, N){
    plot <- ggplot() + 
        geom_path( data = original,  mapping = aes({{E}}, {{N}}, colour = "cyan"), size = 0.8, alpha = 0.2) +
        geom_point(data = original,  mapping = aes({{E}}, {{N}}, colour = "cyan"), alpha = 0.2) + 
        geom_path( data = resampled, mapping = aes({{E}}, {{N}}, colour = "red"),  size = 1) +
        geom_point(data = resampled, mapping = aes({{E}}, {{N}}, colour = "red"),  size = 1.2) +
        theme_bw() +
        theme(legend.justification = "right") +
        theme(plot.title = element_text(face = "bold", hjust = 0.5), legend.title = element_text(face = "bold", hjust = 0.5))

    plot
}
```









