---
title: "Trajectories_2"
output: html_document
date: "`r Sys.Date()`"
---

Trajectories_2

```{r, warning=F, message=F}
rm(list = ls())
```


```{r, warning=F, message=F}
library(ComputationalMovementAnalysisData)
library(tidyverse)
library(sf)
library(readr)        
library(dplyr)        
library(ggplot2)      
library(lubridate)
library(ggpubr)
```


```{r, warning=F, message=F}
ws <- wildschwein_BE
metadata <- wildschwein_metadata
metadata

ws <- merge(ws, metadata[, c("TierID", "Sex")], by = "TierID") 
```


```{r}
ws <- ws %>% filter(TierID == c(10,22,36,40,48)) 

ws <- ws %>% subset(select = - c(day, CollarID, moonilumination))

ws <- ws %>% mutate(dt_rounded = round_date(DatetimeUTC, unit = "minute"))

```


```{r}
ws_caroline <- ws %>% filter(TierID == 10)
ws_miriam <- ws %>% filter(TierID == 22)
ws_olga <- ws %>% filter(TierID == 36)
ws_franz <- ws %>% filter(TierID == 40)
ws_amos <- ws %>% filter(TierID == 48)

ws_caroline_olga_join <- inner_join(ws_caroline, ws_olga, by = "dt_rounded", suffix = c("_caroline", "_olga")) %>% 
                 mutate(distance = sqrt((E_caroline - E_olga)^2 + (N_caroline - N_olga)^2), meet = distance < 30)

ws_franz_amos_join <- inner_join(ws_franz, ws_amos, by = "dt_rounded", suffix = c("_franz", "_amos")) %>% 
                 mutate(distance = sqrt((E_franz - E_amos)^2 + (N_franz - N_amos)^2), meet = distance < 30)

```


```{r}
ggplot() +
  geom_point(data = ws_caroline, aes(x = E, y = N, color = TierName),  alpha = 0.1, size = 0.5) +
  geom_point(data = ws_olga, aes(x = E, y = N, color = TierName), alpha = 0.1, size = 0.5) +
  geom_point(data = ws_caroline_olga_join %>%  filter(meet == TRUE), aes(x = E_caroline, y = N_caroline, fill = TierName_caroline), pch = 21, color = "black") +
  geom_point(data = ws_caroline_olga_join %>%  filter(meet == TRUE), aes(x = E_olga, y = N_olga, fill = TierName_olga), pch = 21, color = "black") #+ theme_void()

```

# -> that's the result without the filter to points with a 60 second interval!

```{r, warning=F, message=F}
rm(list = ls())
```

```{r, warning=F, message=F}
ws <- wildschwein_BE
metadata <- wildschwein_metadata
```


```{r, warning=F, message=F}
# difftime 
ws <- ws %>% group_by(TierID) %>% mutate(timelag = as.integer(difftime(lead(DatetimeUTC), DatetimeUTC, units = "secs"))) %>% 
  ungroup()

# filter to 60 seconds interval
ws <- ws %>% filter(timelag >= 50 & timelag < 70)

ws <- ws %>% subset(select = - c(day, CollarID, moonilumination))

ws <- ws %>% mutate(dt_rounded = round_date(DatetimeUTC, unit = "minute"))

```




# with filter down to 60 second sampling interval:

```{r}
# ws <- ws %>% filter(TierID == c(10,22,36,40,48))
# c(10,22,36,40,48) #those with 60s sampling interval

ws_caroline <- ws %>% filter(TierID == 10)
ws_miriam <- ws %>% filter(TierID == 22)
ws_olga <- ws %>% filter(TierID == 36)
ws_franz <- ws %>% filter(TierID == 40)
ws_amos <- ws %>% filter(TierID == 48)

ws_caroline_olga_join <- inner_join(ws_caroline, ws_olga, by = "dt_rounded", suffix = c("_caroline", "_olga")) %>% 
                 mutate(distance = sqrt((E_caroline - E_olga)^2 + (N_caroline - N_olga)^2), meet = distance < 30)

ws_franz_amos_join <- inner_join(ws_franz, ws_amos, by = "dt_rounded", suffix = c("_franz", "_amos")) %>% 
                 mutate(distance = sqrt((E_franz - E_amos)^2 + (N_franz - N_amos)^2), meet = distance < 30)

```


```{r}
ggplot() +
  geom_point(data = ws_caroline, aes(x = E, y = N, color = TierName),  alpha = 0.1, size = 0.5) +
  geom_point(data = ws_olga, aes(x = E, y = N, color = TierName), alpha = 0.1, size = 0.5) +
  geom_point(data = ws_caroline_olga_join %>%  filter(meet == TRUE), aes(x = E_caroline, y = N_caroline, fill = TierName_caroline), pch = 21, color = "black") +
  geom_point(data = ws_caroline_olga_join %>%  filter(meet == TRUE), aes(x = E_olga, y = N_olga, fill = TierName_olga), pch = 21, color = "black") #+ theme_void()

```

```{r}
meets_caroline_olga <- ws_caroline_olga_join %>% filter(meet == TRUE)

```

# Now code plot with geom_path for each of these meetup groups for both - use meets_caroline_olga for that ?









